### ISSUE TITLE
Ausdruck eines einzelnen Tickets

### ISSUE THREAD

**Issue by krumeich** [moetz87/de.moetz.js.webext.redmineprintplugin#1]
Es wäre sehr hilfreich, wenn man von der Detailansicht eines Tickets aus den Druck dieses einzelnen Tickets starten könnte, statt immer über die Liste der Tickets gehen zu müssen.

**Comment by moetz87** [comment]
Ausdruck eines einzelnen TIckets in der Detailansicht mit der aktuellen Version 1.0.5 hinzugefügt.

**Comment by krumeich** [comment]
Yeah!
